name: Node.js CI

on: [push]

jobs:
  build:
    name: CI job
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.11.0, 14.18.2, 16.13.1, 17.3.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn ci
      - name: Run tests
        run: yarn test
