name: Node.js CI

on: [push]

jobs:
  build:
    name: CI Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12', '14', '16', '17']
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install:ci
      - name: Run tests
        run: yarn test --verbose
